blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/Websoft9/Waterflow/blob/main/README.md
    about: Check our documentation for guides and tutorials
  - name: ðŸ’¡ Discussions
    url: https://github.com/Websoft9/Waterflow/discussions
    about: Ask questions and discuss ideas with the community
